apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ov
  namespace: openshift-gitops
spec:
  destination:
    namespace: ov-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ov
    repoURL: https://github.com/justone0127/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
