apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: rhel9
    vm.kubevirt.io/template: rhel9-server-poc
    vm.kubevirt.io/template.revision: "1"
  name: rhel9
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9
      spec:
        source:
          pvc:
            name: rhel9-2-image
            namespace: rhel9
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain:  rhel9
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
           - disk:
              bus: virtio
             name: rootdisk
           - disk:
              bus: virtio
             name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      nodeSelector:
        node-role.kubernetes.io/metal: ""
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name:  rhel9
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: openshift
              chpasswd:
                expire: false
          name: cloudinitdisk
